### PR TITLE
Write! Editor Added

### PR DESCRIPTION
**Pull request by gutierri**
Write!It is a perfect editor for writing texts with a clean interface and without distractions. Perfect for writers :)

### CODE REVIEW

**Comment by gutierri** [comment]
Excuse me. It has two commits in a pull request :(

**Comment by gutierri** [comment]
Ready!

**Comment by RiseLedger** [comment]
@gutierri Have you personal use this editor? From what I see the simple version do not have unlimited numbers of Ctrl+Z which is not so good. For now I can not accept this editor. Thanks for understanding

**Comment by gutierri** [comment]
Yes. I've used. Limiting the Ctrl + z was never a problem.

**Pull request closed without merging**
