### PR TITLE
Added FreeFileSync to Utilities

### PR DESCRIPTION
**Pull request by vineelkovvuri**
This is an awesome backup utility which gives user complete control over the backup process. It does not create any proprietary backup file. It just copies files and folders in source directory to destination with multiple schemes like mirroring, two way sync, update etc. Very useful!

### CODE REVIEW

**Comment by vineelkovvuri** [comment]
Hi @RiseLedger,  Could you please pull the above request?

**Comment by RiseLedger** [comment]
@vineelkovvuri Have you personal use this tool?

**Comment by vineelkovvuri** [comment]
@RiseLedger of course I use it a lot. Give it a shot.

**Comment by RiseLedger** [comment]
@vineelkovvuri Thanks for contribution

**Pull request merged**
